### ISSUE TITLE
Rest Api

### ISSUE THREAD

**Issue by kikogolk** [alb3rtobr/tfm_swcraftsmanship#1]
The application will expose a RESTAPI to allow the clients make operations over the application.

In a first approach, the API will consist in CRUD operations over a single entity in the database. All the operations done will be stored in a topic in the Kafka bus message.

- [x] Create REST API project made in Spring Cloud.
- [x] Expose some CRUD operations.
- [x] Connect the service with KAFKA.
- [x] Prepare to be deployed in Kubernetes.

**Comment by kikogolk** [comment]
Hi @alb3rtobr @carlosTorres07 ,

It is needed to start thinking about the REST API exposed. Do you have ideas?

**Comment by kikogolk** [comment]
Hi,

If you agree, these will be the mappings supported by the REST API in order to manage Items:

**REST API mappings:**

- List items:
	GET /api/v1/items
- Create item:
	POST /api/v1/items
- Get an item:
	GET /api/v1/items/{id}
- Update an item:
	PUT /api/v1/items/{id}
- Delete an item:
	DELETE /api/v1/items/{id}

**Comment by carlosTorres07** [comment]
I agree with the proposal

**Comment by alb3rtobr** [comment]
+1

**Comment by kikogolk** [comment]
CRUD operations done. I used a Stub in order to simulate the persistence.

I have to make another change. Right now I am storing in Kafka objects of class **ItemOperation**. Currently this class only stores an **Item**, but I have to update it in order to set the kind of operation done (created, updated, deleted, etc).

**Comment by kikogolk** [comment]
**ItemOperation** includes now the type of operation: **CREATED** or **DELETED**.

We can see in the future if we need more types.

COMMIT: 17c83d20c26d24cdc3a1d70a491fede35e896db1
