### ISSUE TITLE
All artifacts services should be generated using docker

### ISSUE THREAD

**Issue by kikogolk** [alb3rtobr/tfm_swcraftsmanship#33]
Due to RestApi and StockChecker services depends on proto-idl project, it is needed to generate proto-idl jar artifact and provide it to the other services in some way. Using Docker for generating the artifacts makes this more complicated.

We have to options:
- Investigate how to solve the issue using Docker multistage or using two different docker build files.
- Making use of a free artifactory repository. This is free, for example: https://mymavenrepo.com/

**Comment by alb3rtobr** [comment]
how to host a maven repo in github: https://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github/14013645#14013645

**Comment by kikogolk** [comment]
Hasta luego Lucas
